_wandb:
    value:
        cli_version: 0.21.0
        e:
            fuafxth845mk5nf6q2b1dy4uggw5ldxk:
                codePath: Revised_Paired_MIMIC_NLP_ATaylor_Project.ipynb
                codePathLocal: Revised_Paired_MIMIC_NLP_ATaylor_Project.ipynb
                colab: https://colab.research.google.com/notebook#fileId=https://github.com/April-Taylor/NLP-Qualifications-Project/blob/main/Revised_Paired_MIMIC_NLP_ATaylor_Project.ipynb
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "253055008768"
                        used: "45964603392"
                email: taylorad@iu.edu
                executable: /usr/bin/python3
                git:
                    commit: 5dd949e61d13afcf0d989a5099177b084ee6b426
                    remote: https://github.com/April-Taylor/NLP-Qualifications-Project.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-4a1bfc20-c79f-35a2-1e52-f1326beb21de
                host: dc0e3c486edf
                memory:
                    total: "89631731712"
                os: Linux-6.1.123+-x86_64-with-glibc2.35
                program: Revised_Paired_MIMIC_NLP_ATaylor_Project.ipynb
                python: CPython 3.11.13
                root: /content/drive/MyDrive/ColabRepos/NLP-Qualifications-Project
                startedAt: "2025-07-17T20:54:31.464137Z"
                writerId: fuafxth845mk5nf6q2b1dy4uggw5ldxk
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 33
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 12
                - 33
                - 41
                - 49
                - 51
                - 53
                - 71
                - 98
                - 105
            "3":
                - 15
                - 16
            "4": 3.11.13
            "5": 0.21.0
            "6": 4.53.2
            "8":
                - 1
                - 12
            "12": 0.21.0
            "13": linux-x86_64
min_score:
    value: 0.75
